//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTask
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public decimal Mark { get; set; }
        public int StudentId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
